project_id = "yjpzqgsrikfnpyyzbpvr"



[functions.preview-transactional-email]
verify_jwt = false



[functions.submit-lead]
verify_jwt = false

[functions.send-contact-internal]
verify_jwt = false

[functions.send-contact-confirmation]
verify_jwt = false
